version: 0.2
  
phases:
  install:
    runtime-versions: 
      golang: 1.14
  build:
    commands:
      - make all

artifacts:
  files:
    - start-service.sh
    - stop-service.sh
    - bin/server
    - appspec.yml
